### PR TITLE
Add @IgnoreUntil Support for "yyyy-MM-dd'T'HH:mm:ss" datetime format #1

### LINKED ISSUE #1: Add @IgnoreUntil Support for "yyyy-MM-dd'T'HH:mm:ss" datetime format
@IgnoreUntil only supports "yyyy-MM-dd" date format.

I would like to extend it to also support a datetime format for more precise control, for example:
"yyyy-MM-dd'T'HH:mm:ss"
```java
@IgnoreUntil("2018-02-18T12:35:00")
```

### PR DESCRIPTION
**Pull request by siladu**
Fixes #1

### CODE REVIEW

**Comment by mrwilson** [comment]
Hi Simon,

Thanks for this pull request! It will be reviewed in the next couple of days.

Kind Regards,

Alex

**Review by mrwilson — CHANGES_REQUESTED** [review]
This looks great. Can you update the documentation in the README to reflect that there are two supported date/time formats?

**Comment by siladu** [comment]
Sorted :)

**Review by mrwilson — APPROVED** [review]

**Comment by mrwilson** [comment]
Looks good to me!

**Pull request merged**
